### PR TITLE
Fix bugs with adding a new Section by copying another

### LINKED ISSUE #450: Adding Section on Template page does not move it to the end (Brian)
After adding a new Section to a Template, it appears somewhere in the middle of the list.  It should always be the last Section in the template.

Image

### PR DESCRIPTION
**Pull request by briri**
## Description

Finishes #486

related to [backend PR](https://github.com/CDLUC3/dmsp_backend_prototype/pull/276) 

**Add new Section page**
- added new `bestPractice` and `filteredBestPractice` states so we can separate them from the affiliation's sections
- added a Load More button to both sections
- added a `visibilityCount` state to help the Load more section show the correct number of sections
- added `handleLoadMore` and `renderLoadMore` functions
- added SCSS module for the new "Load more" button
- updated the function handling the results of fetching the data to separate out the bestPractice sections
- added new translations to support the load more button

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- All existing tests pass
- Verified manually via the UI

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I updated the CHANGELOG.md and added documentation if necessary
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have completed manual or automated accessibility testing for my changes
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: app/[locale]/template/[templateId]/section/new/page.tsx [hunk 1]
```diff
@@ -173,9 +198,46 @@ const SectionTypeSelectPage: React.FC = () => {
...
+  type VisibleCountKeys = keyof typeof visibleCount;
+  // When user clicks the 'Load more' button, display 3 more by default
+  const handleLoadMore = (listKey: VisibleCountKeys) => {
+    setVisibleCount((prevCounts) => ({
+      ...prevCounts,
+      [listKey]: prevCounts[listKey] + 6, // Increase the visible count for the specific list
+    }));
+
+    setTimeout(() => {
+      if (nextSectionsRef.current) {
```
Comment (jupiter007) [inline app/[locale]/template/[templateId]/section/new/page.tsx:214]: You need to apply `nextSectionRef` to your content, like in `/template` so that when the user clicks the `Load more` button, it scrolls down to that location. I calculated it in `/template` using something like `const isFirstInNextSection = index === visibleCount['filteredTemplates'] - 3;`, but in your case it would be `6` instead of `3`

File: app/[locale]/template/[templateId]/section/new/page.tsx [hunk 2]
```diff
@@ -173,9 +198,46 @@ const SectionTypeSelectPage: React.FC = () => {
     // Need this to set list of templates back to original, full list after filtering
     if (searchTerm === '') {
       setFilteredSections(null);
+      setFilteredBestPracticeSections(null);
     }
   }, [searchTerm])
 
+  type VisibleCountKeys = keyof typeof visibleCount;
+  // When user clicks the 'Load more' button, display 3 more by default
```
Comment (jupiter007) [inline app/[locale]/template/[templateId]/section/new/page.tsx:206]: L206: Minor, but your comment says `3` but you are incrementing by `6`

File: app/[locale]/template/[templateId]/section/new/page.tsx (hunk 1 above)
Comment (briri) [reply app/[locale]/template/[templateId]/section/new/page.tsx:217]: thanks. This should be working now

File: app/[locale]/template/[templateId]/section/new/__tests__/page.spec.tsx [hunk 3]
```diff
@@ -223,5 +241,39 @@ describe("SectionTypeSelectPage", () => {
...
+    ]);
+
+    await act(async () => {
+      render(
+        <SectionTypeSelectPage />
+      );
+    });
+
+    // For some reason this does not work although it does for the search button in the test above
+    const loadMoreButtons = screen.getAllByLabelText(/buttons.loadMore/i);
```
Comment (briri) [inline app/[locale]/template/[templateId]/section/new/__tests__/page.spec.tsx:265]: @jupiter007 I cannot figure out how to make this work. It cannot find the buttons. I've tried giving them each an individual label and it just won't grab it. You can even see the buttons in the log output it provides

Comment (jupiter007) [reply app/[locale]/template/[templateId]/section/new/__tests__/page.spec.tsx:265]: > @jupiter007 I cannot figure out how to make this work. It cannot find the buttons. I've tried giving them each an individual label and it just won't grab it. You can even see the buttons in the log output it provides

Ok I'll take a look @briri

Comment (briri) [reply app/[locale]/template/[templateId]/section/new/__tests__/page.spec.tsx]: thanks! I just updated it

**Review by jupiter007 — APPROVED** [review]

File: app/[locale]/template/[templateId]/section/new/__tests__/page.spec.tsx (hunk 3 above)
Comment (jupiter007) [reply app/[locale]/template/[templateId]/section/new/__tests__/page.spec.tsx]: Thanks @briri. I approved the PR.
