### PR TITLE
Fixed issue where existing title doesn't show when editing template name/title

### LINKED ISSUE #475: Edit Template name should have existing name in there
When you click to edit Template name, the current Name should be in the text field to start with.

### PR DESCRIPTION
**Pull request by andrewebdev**
## Description

Fixed but where the template name is blank when editing the name for an existing
template.

To facilitate this fix I had to clean up a lot of events and effects, that were
all either redundant, causing confusion, or causing blocking effect updates.

Fixes #475

## Type of change
Please delete options that are not relevant

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- I tested this manulaly by editing the title, changing it etc.
- I updated the existing tests to verify my changes.
- I also ensured that existing tests pass so that I didn’t introduce new errors.

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I updated the CHANGELOG.md and added documentation if necessary
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have completed manual or automated accessibility testing for my changes
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: components/PageHeaderWithTitleChange/index.tsx [hunk 1]
```diff
@@ -38,19 +34,24 @@ const PageHeaderWithTitleChange: React.FC<PageHeaderProps> = ({
...
   actions,
   className = '',
-  handleInputChange,
-  handleTitleChange,
-  newTitle = '',
+  onTitleChange,
 }: PageHeaderProps) => {
 
   const [isEditing, setIsEditing] = useState(false);
+  const [newTitle, setNewTitle] = useState<string>(title);
```
Comment (jupiter007) [inline components/PageHeaderWithTitleChange/index.tsx:41]: @andrewebdev, I feel that the `PageHeaderWithTitleChange` component should not manage the state of the `title`. That should stay with the `TemplateEditPage` so that PageHeaderWithTitleChange can remain stateless. I think it's better to have separation of concerns.

Comment (jupiter007) [reply components/PageHeaderWithTitleChange/index.tsx:41]: To solve this issue without moving the "setTitle" state to `PageHeaderWithTitleChange`, you can do the following simple change:

1) In the `TemplateEditPage` component:
- Set the `newTitle` in the useEffect
```
  // Need to set this info to update template title
  useEffect(() => {
    if (data?.template) {
      setTemplateInfoState({
        templateId: Number(data.template.id),
        name: data.template.name || '',
        visibility: data.template.visibility || null,
      });
      // Set newTitle to the template name only if newTitle is not already set
      if (!newTitle) {
        setNewTitle(data.template.name || '');
      }
    }
  }, [data]);
```
- Remove the `newTitle` prop from `PageHeaderWithTitleChange` and set `title={newTitle}`:
```
      <PageHeaderWithTitleChange
        title={newTitle}
        description={description}
        showBackButton={false}
        breadcrumbs={
          <Breadcrumbs>
            <Breadcrumb><Link href="/">{BreadCrumbs('home')}</Link></Breadcrumb>
            <Breadcrumb><Link href="/template">{BreadCrumbs('templates')}</Link></Breadcrumb>
            <Breadcrumb>{template.name}</Breadcrumb>
          </Breadcrumbs>
        }
        className="page-template-overview"
        handleTitleChange={handleTitleChange}
        handleInputChange={handleInputChange}
      />
```
2) In the `PageHeaderWithTitleChange`:
- Remove the `newTitle` prop from the component
- Change `value` in `<FormInput>` to equal `title || ''`:
```
              <FormInput
                name="templateTitle"
                type="text"
                label="Template title"
                value={title || ''}
                inputClasses="titleChange-input"
                placeholder="Enter new template title"
                onChange={handleInputChange}
              />
```
and please hard-code the `name` to something like `templateTitle`.

Comment (jupiter007) [reply components/PageHeaderWithTitleChange/index.tsx:41]: @andrewebdev yes, the initial implementation used `newTitle` and `title` which was not optimal, but the changes I suggested above is only using `title` and it keeps state management of `newTitle` in the parent `TemplateEditPage`, rather than moving it to `PageHeaderWithTitleChange`.

With your solution, you have two separate state variables tracking the same logical piece of data:
- `title` is passed to PageHeaderWithTitleChange as `template.name`. In PageHeaderWithTitleChange, you are tracking title changes with the state `const [newTitle, setNewTitle] = useState<string>(title);`. We could have syncing issues, and in general we want to keep the editing state in the parent.

Comment (jupiter007) [reply components/PageHeaderWithTitleChange/index.tsx:41]: @andrewebdev - I'm going to go ahead and approve your changes. Later, we should probably think of another way to do this so that we don't have state changes for `title` in the shared PageHeaderWithTitleChange component.
